spring.application.name=jwtDemo

server.port=0
# spring.datasource.url=jdbc:mysql://localhost:3306/jwtdb
# spring.datasource.username=root
# spring.datasource.password=root@123

# spring.datasource.url = jdbc:mysql://localhost:3306/jwtdb
# spring.datasource.username = root
# spring.datasource.password= Jr@721260
# spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver

spring.datasource.url = jdbc:mysql://cartnova_db_birthdayto:448f50a06108a8f1e39eb22817d2a245b2c40568@07fc37.h.filess.io:3306/cartnova_db_birthdayto
spring.datasource.username = cartnova_db_birthdayto
spring.datasource.password= 448f50a06108a8f1e39eb22817d2a245b2c40568
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=YiG6RBZqK76TWTwsTEF1YDs73ACbvy8g6VKQPeqAHrF
app.jwt.expiration-ms=3600000

razorpay.key-id=rzp_test_Spd3vcWXnK1zc8
razorpay.key-secret=W8gBoNYVat4fG7tBF1XqzQlY
razorpay.currency=INR





# Limit the connection pool size for Filess.io Free Tier
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=20000

